#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIUtility.LinqToSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	using WebAPIUtility.Help;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MPS_PM")]
	public partial class WorkingDayUSDataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWorkingDayUSModel(WorkingDayUSModel instance);
    partial void UpdateWorkingDayUSModel(WorkingDayUSModel instance);
    partial void DeleteWorkingDayUSModel(WorkingDayUSModel instance);
		#endregion

		public WorkingDayUSDataClassDataContext() :
				base(Cryptography.Decrypt(global::System.Configuration.ConfigurationManager.ConnectionStrings["MPS_PMConnectionString"].ConnectionString, "$Mps.ConnStrKey#2022"), mappingSource)
		{
			OnCreated();
		}

		public WorkingDayUSDataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayUSDataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayUSDataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayUSDataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WorkingDayUSModel> WorkingDayUSModels
		{
			get
			{
				return this.GetTable<WorkingDayUSModel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SPM_WORKING_DAY_US_VEW")]
	public partial class WorkingDayUSModel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _WORKING_DAY;
		
		private byte _WEEK_NUMBER;
		
		private short _YEAR;
		
		private byte _MONTH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnWorkingDayChanging(System.DateTime value);
    partial void OnWorkingDayChanged();
    partial void OnWeekNumberChanging(byte value);
    partial void OnWeekNumberChanged();
    partial void OnYearChanging(short value);
    partial void OnYearChanged();
    partial void OnMonthChanging(byte value);
    partial void OnMonthChanged();
    #endregion
		
		public WorkingDayUSModel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ID", Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="WORKING_DAY", Storage="_WORKING_DAY", DbType="Date NOT NULL")]
		public System.DateTime WorkingDay
		{
			get
			{
				return this._WORKING_DAY;
			}
			set
			{
				if ((this._WORKING_DAY != value))
				{
					this.OnWorkingDayChanging(value);
					this.SendPropertyChanging();
					this._WORKING_DAY = value;
					this.SendPropertyChanged("WorkingDay");
					this.OnWorkingDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="WEEK_NUMBER", Storage="_WEEK_NUMBER", DbType="TinyInt NOT NULL")]
		public byte WeekNumber
		{
			get
			{
				return this._WEEK_NUMBER;
			}
			set
			{
				if ((this._WEEK_NUMBER != value))
				{
					this.OnWeekNumberChanging(value);
					this.SendPropertyChanging();
					this._WEEK_NUMBER = value;
					this.SendPropertyChanged("WeekNumber");
					this.OnWeekNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="YEAR", Storage="_YEAR", DbType="SmallInt NOT NULL")]
		public short Year
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MONTH", Storage="_MONTH", DbType="TinyInt NOT NULL")]
		public byte Month
		{
			get
			{
				return this._MONTH;
			}
			set
			{
				if ((this._MONTH != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._MONTH = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
